apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: babayo-api
  name: babayo-api
spec:
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: 10107
  - port: 80
    name: http
    protocol: TCP
    targetPort: 443
  selector:
    app: babayo-api
