apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: babayo-api
  name: babayo-api
  annotations:
      # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:483132274140:certificate/eb1e0ba1-4f9e-4a32-84e0-f69858eca6a0
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    
spec:
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: 10107
  - port: 80
    name: http
    protocol: TCP
    targetPort: http
  selector:
    app: babayo-api
